### ISSUE TITLE
Error when using alt-contigs for Tiddit-sv

### ISSUE THREAD

**Issue by SarahBeecroft** [SciLifeLab/TIDDIT#103]
Hi, 

I'm not sure if this is a bug, but I've has the following error using 3.3.1 and 3.4.0 versions of Tiddit. 

```
Traceback (most recent call last):
    File "/usr/local/bin/tiddit", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.9/site-packages/tiddit/__main__.py", line 151, in main
      tiddit_contig_analysis.main(prefix,sample_id,library,contigs,coverage_data,args)
    File "tiddit/tiddit_contig_analysis.pyx", line 133, in tiddit.tiddit_contig_analysis.main
    File "tiddit/tiddit_contig_analysis.pyx", line 57, in tiddit.tiddit_contig_analysis.read_contigs
  KeyError: 'HLADRB1*04:03:01'
```

It seems like perhaps it's some sort of parsing error, because looks like it should be formatted as HLA-DRB1\*04:03:01 (i.e. it's missing a dash). So HLADRB1*04:03:01 is "missing" from my input file because the query is malformed, possibly? I should mention this only seems to be an issue on one of my inputs (Platinum genome ERR194159, using the fasta reference from Sarek iGenome Homo_sapiens_assembly38.fasta). 

Do you have any suggestions or fix for this one? Please let me know if you'd like more info. 

Thanks very much!

Sarah

**Comment by J35P312** [comment]
Hello!
Though luck! But very observant of you to find the missing - !
Did you align the ERR194159 data to Sarek iGenome Homo_sapiens_assembly38.fasta; or did you download the bam file? If you downloaded bam file, I would reccomend you to first make sure that the contig names in the fasta and bam file match:

You could try something like this:

samtools view -H <bamfile.bam> | grep "DRB1*04:03:01" 

grep "DRB1*04:03:01" Homo_sapiens_assembly38.fasta

Are they both containing the - (i.e did tiddit lose it somewhere)?

As a quickfix, you could try disable the assembly step, that will however worsen the performance of small variants.

--skip_assembly

You could also try giving TIDDIT a reference with only autosomes and sexchromosomes, that way it wont align to contigs that are not in the bam header (I have never tried doing so however...).

Good luck, and keep me updated!

**Comment by SarahBeecroft** [comment]
Hi,

Thanks for getting back so fast 😊

I did the alignment myself. The grep on the bam showed that there was nothing matching "DRB1*04:03:01", but there was a match for the version with the dash. I had originally thought I needed to remove some strange read in my bam file.

My colleague had success with the autosome/sex chromosome reference approach, but we thought it might be good to report this anyway. We are aiming to put tiddit into a nice SV calling pipeline! 😊



Thanks very much!



Sarah



From: Jesper Eisfeldt ***@***.***>
Date: Monday, 6 February 2023 at 6:03 pm
To: SciLifeLab/TIDDIT ***@***.***>
Cc: SarahBeecroft ***@***.***>, Author ***@***.***>
Subject: Re: [SciLifeLab/TIDDIT] Error when using alt-contigs for Tiddit-sv (Issue #103)

Hello!
Though luck! But very observant of you to find the missing - !
Did you align the ERR194159 data to Sarek iGenome Homo_sapiens_assembly38.fasta; or did you download the bam file? If you downloaded bam file, I would reccomend you to first make sure that the contig names in the fasta and bam file match:

You could try something like this:

samtools view -H <bamfile.bam> | grep "DRB1*04:03:01"

grep "DRB1*04:03:01" Homo_sapiens_assembly38.fasta

Are they both containing the - (i.e did tiddit lose it somewhere)?

As a quickfix, you could try disable the assembly step, that will however worsen the performance of small variants.

--skip_assembly

You could also try giving TIDDIT a reference with only autosomes and sexchromosomes, that way it wont align to contigs that are not in the bam header (I have never tried doing so however...).

Good luck, and keep me updated!
