### ISSUE TITLE
Parameters for exome seq data

### ISSUE THREAD

**Issue by MatLienhard** [SciLifeLab/TIDDIT#112]
Hello TIDDIT Developers,

I'm planning to use TIDDIT for structural variant (SV) calling from exome sequencing data. I have a few questions regarding the parameters:

1. When using TIDDIT for SV calling from exome sequencing data, do I need to specify any additional parameters specific to exomes? Or will the tool handle the analysis automatically based on the input data?

2. The `-c` parameter allows setting the average coverage. The help mentions that it would be useful for exome or panel data. How should I set the coverage for exome sequencing data? Are there any guidelines or recommendations?

3. Apart from the `-c` parameter, are there any additional parameters I should consider adjusting for exome data?
  
Please provide guidance on the appropriate parameter settings for exome SV calling. Thank you!

Best regards,
Matthias

**Comment by J35P312** [comment]
Hello!
And thanks for trying out TIDDIT! TIDDIT can detect variation in exome or panel data, but the classification and filtering (I.e whether or not the FILTER column will be set to PASS or not) is unreliable in panel data. Translocations and inversions are properly classified, duplications and deletions are likely to be classified as BND. 

1. I recomend using default settings, except for the -c parameter. Next, you may need to apply downstream filters, such as frequency database, or apply a more stringent cut-off for the number of reads and split reads (using bcftools for instance).

2. You can either calculate the coverage across the exome using some tool, like Mosdepth (https://github.com/brentp/mosdepth); but you can also provide a good guess. This is more for cosmetic purposes, and wont affect the variant detection. If the coverage is uneven you may also want to set the --max_coverage parameter to a high number (like 99999). --max_coverage is mainly for genomes, to avoid calling to many false positives in centromeres etc. 

Good luck!
//jesper

**Comment by MatLienhard** [comment]
Thank you for your suggestions.
