### ISSUE TITLE
BWA index error

### ISSUE THREAD

**Issue by sreerampeela** [SciLifeLab/TIDDIT#113]
Similar to the issue #89 
I am using a docker image quay.io/biocontainers/tiddit:3.6.1--py38h24c8ff8_0

Created ref genome indexes using bwa ( bwa index -p ref ref.fa) as instructed. Following files are generated:
ref.amb, ref.ann, ref.pac,  ref.bwt,  ref.sa

However the error still persists:
"error, The reference must be indexed using bwa index; run bwa index, or skip local assembly (--skip_assembly)"

How to change the glob in TIDDIT docker image?

**Comment by J35P312** [comment]
Hello!
Sorry for slow reply, I have been away on holiday. Currently, it is not possible to change the glob, instead you must run bwa index using the default settings, so that the prefix becomes the same as the fasta file name:

bwa index ref.fa

good luck!
//jesper
