### ISSUE TITLE
How genotype are assigned ? 

### ISSUE THREAD

**Issue by npatel22526** [SciLifeLab/TIDDIT#35]
Hello, 

It seems great approach to incorporate coverage along with split read and discordant read. 
I am trying TIDDIT and come across an issue. When I looked at genotype in VCF it has 3 categories 
./1, 0/1, 1/1. The latter two are understood but what does "./1" represents? 50% of deletions have that genotype. 

Thanks, 
Nick

**Comment by J35P312** [comment]
Hello!
Sorry for the delay!
I have forgot to keep this repository updated. Now there should not be any ./1 genotypes.
The ./1 genotype means that tiddit could not determine if the genotype is het or hom.
