### ISSUE TITLE
Inverted DUP

### ISSUE THREAD

**Issue by dnil** [SciLifeLab/TIDDIT#39]
A random thought: does the current clustering handle inverted dups? How are they classified?

**Comment by J35P312** [comment]
Hello there!
Both yes and no! We do have all the information to classify inverted duplications, but TIDDIT is not really doing it.
Instead, such variant will be reported as an inversion, and the positions of this inversion will correspond to the duplicated region.
There will be no indication that this is an inverted duplication, but  if you check the covM flag, it should be about 50% higher  than the average coverage.
I should try to add some more information to this, sadly there is no "inverted duplication" tag specified by the vcf format, so we have to choose either to report it as an inversion or a duplication, or  invent our own tag...Which would you prefer?

**Comment by dnil** [comment]
Subtypes perhaps? Like DUP::INV DUP::TDUP DUP::IDUP. Next will then be aggregates with major and minor type, like: INV::DEL-INV-DEL!

**Comment by dnil** [comment]
Ping on this @J35P312... 😊

**Comment by J35P312** [comment]
I got some ideas! I will have a look at it next week =P.

**Comment by dnil** [comment]
Looks like we can close this now! If it needs more testing, feel free to reopen. Nicely done anyway! 🥇
