### ISSUE TITLE
wrong outputs?

### ISSUE THREAD

**Issue by arkyl** [SciLifeLab/TIDDIT#49]
Hi,
I use the following cmd "TIDDIT --sv -b NA12878_S10_R1_001.bam -o NA12878_S10_R1_001.bam.out.vcf". The results are NA12878_S10_R1_001.bam.out.vcf.tab and NA12878_S10_R1_001.bam.out.vcf.signals.tab; however, there is no sv vcf output. The NA12878_S10_R1_001.bam.out.vcf.tab are the coverage data. The NA12878_S10_R1_001.bam.out.vcf.signals.tab seems to be the parsing result of a bam for each read. I think I may miss something. Is there a vcf of output SVs? Thanks a lot!

Yue

**Comment by J35P312** [comment]
Hello there!
You are correct, the vcf file is missing, but this is a good start!
A while ago I moved the vcf module to the python wrapper (it saves me some time when developing).
If you run TIDDIT using the python wrapper, you should get a vcf as well:

python TIDDIT.py  --sv --help

Good luck, and happy benchmarking!

**Comment by arkyl** [comment]
Hi,
Thanks for the reply. I used the python module
python ~/software_installed/TIDDIT/TIDDIT.py --sv --bam
NA12878_S10_R1_001.bam -o NA12878_S10_R1_001.bam.TIDDIT.new --ref
../hs38DH.fa.
However, it seemed that I still didn't get the vcf. This time I get another
file
NA12878_S10_R1_001.bam.TIDDIT.new.db. But still not SV vcf.

Any thoughts about this? Thanks very much!

Yue

**Comment by J35P312** [comment]
That's tricky, your command is correct. 
What output do you get? Do you get any errors from TIDDIT? 
Also what data are you using? TIDDIT has only been tested on Illumina paired-end and mate-pair data!

**Comment by J35P312** [comment]
Then there should be nothing wrong with the data! I usually run that type of data myself.
I usually run a small region for quick testing, such as the begining of chromosome 18:

samtools view -bh /home/jesper/external_data/bam_file/P901_110_noDup.bam chr18:1-1000000 > test.bam

1-10 or so mbp is fine, then you should get some variants. When running, tiddit will print this text:

LIBRARY STATISTICS
	 total reads number 69569
	 total mapped reads 57143
	 total unmapped reads 411
	 split reads 10504
	 low quality reads 12015
	 wrongly contig 5138
	 singletons 76
	total 57143
	Coverage statistics
	C_A = 0.00157923
	S_A = 0.00846382
	C_M = 0.00141217
	C_W = 1.33257e-05
	C_S = 2.12326e-06
	C_D = 0.000150624
	Read length = 86
	Mean Insert length = 2774.27
	Std Insert length = 1364.08
----------
library stats time consumption= 48s
auto-config orientation: outtie
insert size threshold:8230
working on seqence chr18
variant calling time consumption= 0s
clustering signals on chromosome:
chrM
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr21
chr22
chrX
chrY
chr1_gl000191_random
chr1_gl000192_random
chr4_ctg9_hap1
chr4_gl000193_random
chr4_gl000194_random
chr6_apd_hap1
chr6_cox_hap2
chr6_dbb_hap3
chr6_mann_hap4
chr6_mcf_hap5
chr6_qbl_hap6
chr6_ssto_hap7
chr7_gl000195_random
chr8_gl000196_random
chr8_gl000197_random
chr9_gl000198_random
chr9_gl000199_random
chr9_gl000200_random
chr9_gl000201_random
chr11_gl000202_random
chr17_ctg5_hap1
chr17_gl000203_random
chr17_gl000204_random
chr17_gl000205_random
chr17_gl000206_random
chr18_gl000207_random
chr19_gl000208_random
chr19_gl000209_random
chr21_gl000210_random
chrUn_gl000211
chrUn_gl000212
chrUn_gl000213
chrUn_gl000214
chrUn_gl000215
chrUn_gl000216
chrUn_gl000217
chrUn_gl000218
chrUn_gl000219
chrUn_gl000220
chrUn_gl000221
chrUn_gl000222
chrUn_gl000223
chrUn_gl000224
chrUn_gl000225
chrUn_gl000226
chrUn_gl000227
chrUn_gl000228
chrUn_gl000229
chrUn_gl000230
chrUn_gl000231
chrUn_gl000232
chrUn_gl000233
chrUn_gl000234
chrUn_gl000235
chrUn_gl000236
chrUn_gl000237
chrUn_gl000238
chrUn_gl000239
chrUn_gl000240
chrUn_gl000241
chrUn_gl000242
chrUn_gl000243
chrUn_gl000244
chrUn_gl000245
chrUn_gl000246
chrUn_gl000247
chrUn_gl000248
chrUn_gl000249

do you see similar text? Or do you get any python error message? It seems something goes wrong in the python wrapper. If you post the entire TIDDIT output message I may find whats going on!
no problems, and thanks for your patience!

**Comment by arkyl** [comment]
Hi,
Thanks for the detailed reply. I tested on a chr22 regional bam from
20Mb-30Mb and it output the SV vcf. I will test it on the whole chr22. Note
that the bam was based on hg38 so there are many alt contigs. Thanks much.
Yue

**Comment by J35P312** [comment]
It's great to hear that it works for a regional bam! Very recently (like two days ago or so) I fixed a bug in TIDDIT which made it crash on some genomes. I think it should work if you download TIDDIT again and run the entire bam like you ran your regional bam.

Have a look at the closed issue if you want, it's the most recent one:

IndexError: index 13 is out of bounds for axis 0 with size 13

**Comment by arkyl** [comment]
Thanks for the reply. The chr22 works and the whole genome crashes again at
the last step. It indeed has the following error.

IndexError: index 23 is out of bounds for axis 0 with size 23


I will download TIDDIT again and rerun the whole thing. Thanks very much.
Yue

**Comment by arkyl** [comment]
Hi,
The new TIDDIT works and outputs the sv vcf. Thanks very much!
Yue

**Comment by J35P312** [comment]
That's great news!
Thank you too!
//Jesper
