### ISSUE TITLE
IndexError: index 13 is out of bounds for axis 0 with size 13

### ISSUE THREAD

**Issue by YiweiNiu** [SciLifeLab/TIDDIT#50]
Hi,

I used TIDDIT to call SVs but encountered the following error:
```shell
variant calling time consumption= 4878s
Traceback (most recent call last):
  File "/home/work01/tools/TIDDIT/TIDDIT.py", line 54, in <module>
    TIDDIT_clustering.cluster(args)
  File "TIDDIT_clustering.py", line 681, in TIDDIT_clustering.cluster
    header,chromosomes,library_stats=signals(args,coverage_data)
  File "TIDDIT_clustering.py", line 164, in TIDDIT_clustering.signals
    coverage_data[chrB][int(math.floor(posB/100)),2]+=1
IndexError: index 13 is out of bounds for axis 0 with size 13
```

And another small question, there are two identical parameters when typing `python TIDDIT.py --sv -h`
```shell
-m M             minimum variant size,(default = 100)
-z Z             minimum variant size (default=100)
```

What's the differences of these two?

Thanks in advance!

**Comment by J35P312** [comment]
Hi there!
I fixed that bug a while ago, but I forgot to push the changes. If you try the  latest TIDDIT, the problems should be fixed. Sorry about that!

the -m parameter is not used anymore, but I have forgotten to remove it. Well spotted, I will remove it the next update! the -z parameter is really the parameter controlling the  minimum variant size.

Regards
Jesper

**Comment by YiweiNiu** [comment]
Thanks for your quick reply! It works now!

**Comment by J35P312** [comment]
Thanks, that's great!
//JEsper
