### ISSUE TITLE
reference not required

### ISSUE THREAD

**Issue by hurleyLi** [SciLifeLab/TIDDIT#52]
Hi, just to confirm that ITDDIT does not require reference to run anymore, is that correct?

Thanks,
Hurley

**Comment by hurleyLi** [comment]
So.... the executable file in bin/ does not work as mentioned in #49 . So do you suggest not using it for now? The wrapper seems still use the reference.

**Comment by J35P312** [comment]
Hello there!
You are correct, the reference is required, and you must run the SV calling through the python wrapper, which will produce the final output vcf. I will update the README file to clearify this!
Thanks, and have a nice weekend!
//Jesper
