### ISSUE TITLE
Small homozygous deletion (call het)

### ISSUE THREAD

**Issue by jessada** [SciLifeLab/TIDDIT#57]
![screen shot 2018-09-24 at 16 55 27](https://user-images.githubusercontent.com/1397809/45959748-ecd70f80-c01a-11e8-8be9-ced3045bd6ee.png)

The sample in the middle was called 0/1 by FindSV/TIDDIT.

vcf record in TIDDIT
16      89596675        SV_22209_1      N       <DEL>   .       PASS    SVTYPE=DEL;CIPOS=-303,0;CIEND=0,252;END=89621394;SVLEN=24720;COVM=0.0921832022299;COVA=30.8620200268;COVB=28.228429712;LFA=27;LFB=33;LTE=22;E1=5;E2=16;OR=0,0,0,22;ORSR=0,0;QUALA=54;QUALB=53   GT:CN:DV:RV     0/1:2:22:0

**Comment by J35P312** [comment]
Woopsiedaisy, I see I made a typo which disabeled the read-depth based CNV genotype classification.
Now it  is fixed!
