### ISSUE TITLE
ERROR AFTER INSTALLING sys.path.insert(0,'{}/src/'.format(wd)) 

### ISSUE THREAD

**Issue by bibbers93** [SciLifeLab/TIDDIT#60]
Dear developers, I have downloaded and installed TIDDIT as per the details given on this website and I am receiving the following error 

```
Traceback (most recent call last):
  File "/home/s1667153/TIDDIT/TIDDIT.py", line 7, in <module>
    sys.path.insert(0, '{}/src/'.format(wd))
ValueError: zero length field name in format
```

Originally, TIDDIT was installed by my server manager for global use as a module, but this error arose so instead we decided to install and compile locally in my home directory yet the error persists. 

We have used the following command to run TIDDIT

```
$ ~/TIDDIT/TIDDIT.py --sv --bam ../RAW_DATA/BLUE1.bam
```

Please can you help :)

**Comment by J35P312** [comment]
Good evening!
What version of python are you using? TIDDIT should work with python 2.7, older (and probably newer =P) versions of python may produce such error messages.
Have you tried making a conda environment for TIDDIT? That usually works!

Good luck!

**Comment by bibbers93** [comment]
Hi! thank you for your prompt reply. I admit I was using python 2.6.6! 

I have since loaded python 2.7.15 (the only other version I have) and now get the following errors: 

```
/home/s1667153/TIDDIT/TIDDIT.py:8: RuntimeWarning: compiletime version 2.6 of module 'TIDDIT_calling' does not match runtime version 2.7
  import TIDDIT_calling
/home/s1667153/TIDDIT/TIDDIT.py:8: RuntimeWarning: compiletime version 2.6 of module 'DBSCAN' does not match runtime version 2.7
  import TIDDIT_calling
/home/s1667153/TIDDIT/TIDDIT.py:8: RuntimeWarning: compiletime version 2.6 of module 'TIDDIT_coverage' does not match runtime version 2.7
  import TIDDIT_calling
/home/s1667153/TIDDIT/TIDDIT.py:8: RuntimeWarning: compiletime version 2.6 of module 'TIDDIT_filtering' does not match runtime version 2.7
  import TIDDIT_calling
Traceback (most recent call last):
  File "/home/s1667153/TIDDIT/TIDDIT.py", line 8, in <module>
    import TIDDIT_calling
  File "TIDDIT_calling.py", line 12, in init TIDDIT_calling (TIDDIT_calling.c:9293)
    import TIDDIT_filtering
  File "TIDDIT_filtering.py", line 3, in init TIDDIT_filtering (TIDDIT_filtering.c:4339)
    from scipy.stats import norm
```

Do i need to re-compile the system under python 2.7.15 to correct this?

**Comment by bibbers93** [comment]
to add, I have since re-downloaded/ compiled with Python 2.7.15 and get errors related to scipy. Will now try to figure this out before continuing with TIDDIT :)

**Comment by J35P312** [comment]
Welll done! Getting Scipy and numpy to be friends is usually the trickiest part.
Hope you find yout variants! =P
//JEsper
