### ISSUE TITLE
Error when using CRAM file as input

### ISSUE THREAD

**Issue by fgvieira** [SciLifeLab/TIDDIT#64]
When running TIDDIT with a CRAM file, i get the error:
```
BAM file has no @HD SO:<SortOrder> attribute: it is not possible to determine the sort order
Traceback (most recent call last):
  File "/services/tools/tiddit/2.7.0/TIDDIT.py", line 65, in <module>
    TIDDIT_calling.cluster(args)
  File "TIDDIT_calling.py", line 190, in TIDDIT_calling.cluster
    coverage_data=TIDDIT_coverage.coverage(args)
  File "TIDDIT_coverage.py", line 8, in TIDDIT_coverage.coverage
    for line in open(args.o+".tab"):
IOError: [Errno 2] No such file or directory: 'OUTPUT.tab'
```

Looking a bit more, it seems that it is the `cov` module that fails, even though the CRAM file has the attribute:
```
@HD     VN:1.6  SO:coordinate
```

Does TIDDIT support CRAM files?
thanks,

**Comment by J35P312** [comment]
Hello there!
That is correct, Tiddit only support Bam file. I will add cram support, but i need to make some larger changes to Tiddit first (it uses the bamtools api, that do not support cram).

Sorry for the messy error message, that one i can fix easier!
//Jesper
