### ISSUE TITLE
VCF header

### ISSUE THREAD

**Issue by aakrosh** [SciLifeLab/TIDDIT#70]
When I run TIDDIT v2.8.1, the header of the generated VCF has a line describing the INFO field 'OR' as
```
##INFO=<ID=OR,Number=4,Type=Integer,Description="Orientation of the pairs (FF,FR,RF,FR)">
```

Should it be
```
##INFO=<ID=OR,Number=4,Type=Integer,Description="Orientation of the pairs (FF,FR,RF,RR)">
```

or am I mistaken?

**Comment by J35P312** [comment]
Hello there!
Woopsiedaisy! You are correct, that header line is wrongly formated.
I had a look in the source code, and the correct header should be like this:

##INFO=<ID=OR,Number=4,Type=Integer,Description="Orientation of the pairs (FF,RR,RF,FR)">

I will make a quickfix tomorrow, thanks for your feedback!
//JEsper
