### ISSUE TITLE
bwa index error

### ISSUE THREAD

**Issue by cmatKhan** [SciLifeLab/TIDDIT#89]
Hi all,

I am using bwa version ` 0.7.17-r1188`, and the output of `bwa index` is this following for my genome file:

```
kn99_chr1.fasta.0123         kn99_chr1.fasta.ann          kn99_chr1.fasta.pac
kn99_chr1.fasta.amb          kn99_chr1.fasta.bwt.2bit.64
```

My working directory from which I am launching TIDDIT looks like this (the index files are all symlinked into the $PWD)

```
A1_35_8_markdup.bam          kn99_chr1.fasta.0123         kn99_chr1.fasta.pac
A1_35_8_markdup.bam.bai      kn99_chr1.fasta.amb          versions.yml
bwamem2                      kn99_chr1.fasta.ann
kn99_chr1.fasta              kn99_chr1.fasta.bwt.2bit.64
```

and my TIDDIT command looks like this:

```
tiddit \
    --sv \
    -n 1 \
    --bam A1_35_8_markdup.bam \
    --ref kn99_chr1.fasta \
    -o A1_35_8
```

I am getting this error message:

```
error, The reference must be indexed using bwa index
```

which is occurring in `__main__.py` between lines 72 to 74:

```

			if not os.path.isfile(args.ref+".bwt") and not os.path.isfile(args.ref+".64.bwt"):
				print ("error, The reference must be indexed using bwa index")
				quit()

```
Am I doing something wrong with `bwa index`, or is TIDDIT expecting a different version than I am using?

**Comment by J35P312** [comment]
Hello!
Woopsiedaisy! I have made a quick fix, making tiddit glob the following 

    if not glob.glob("{}*.bwt*".format(args.ref)):

This should work for you, feel free to try!

 bwa version 0.7.17-r1188 should work fine. But you should double check the index if you run into problems. could it be that the index is built using bwa-mem 2?

Good luck!

**Comment by cmatKhan** [comment]
yes, it is the case that I am indexing using bwa-mem2 -- my bad.

thank you for addressing this, nonetheless.
