### ISSUE TITLE
FORMAT/LQ value always the same

### ISSUE THREAD

**Issue by fgvieira** [SciLifeLab/TIDDIT#93]
`FORMAT/LQ` is specified as two `Float`s in the header but it seems the values are always equal (`LQ:0.465656,0.465656`). Is this expected? Or are they different in some edge cases?
thanks,

**Comment by J35P312** [comment]
No! It is not supposed to be the same!

I had a look:

sample_data[sample]={}
sample_data[sample]={"covA":coverageA,"**QA":frac_low_qA**,"discA":n_discsA,"splitA":n_splitsA,"refRA":crossing_r_A,"refFA":crossing_f_A}                      sample_data[sample].update({"covB":coverageB,"**QB":frac_low_qA**,"discB":n_discsB,"splitB":n_splitsB,"refRB":crossing_r_B,"refFB":crossing_f_B})

I will fix it next week, thanks for the bug hunting ;P.

**Comment by J35P312** [comment]
Now it is fixed!
