### ISSUE TITLE
get_gc creates format restriction for reference fasta

### ISSUE THREAD

**Issue by cpalmer718** [SciLifeLab/TIDDIT#99]
I'm having to work with a version of a reference genome that has been modified internally, and in the process, the description lines for each chromosome/etc. have gained an extra `>` character in the description itself. This breaks get_gc [here](https://github.com/SciLifeLab/TIDDIT/blob/2bd94921ef2df4b08967e8f76fb10bc94730715d/tiddit/tiddit_coverage_analysis.pyx#L22). Perhaps it would be possible to use `re.split("\n>|^>", sequence)` or similar instead, so that the string parse is more resilient to idiosyncrasies of the input fasta? Thanks!

**Comment by J35P312** [comment]
Hello!
Though luck!

re.split("\n>|^>", sequence)

sounds like a good idea, I will give it a try! Thanks for the suggestion
//Jesper

**Comment by J35P312** [comment]
Hello again!
I tested re.split("\n>|^>", sequence), it works nicely! Thanks for the suggestion.
I have added it to TIDDIT 3.5.0

//Jesper
